### ISSUE TITLE
Linkable no longer maintained

### ISSUE THREAD

**Issue by sanderha** [dynamic/silverstripe-elemental-baseobject#15]
sheadawsons linkable module is no longer maintained, also does not implement any for of permission handling. 
Instead, this module is recommended: https://github.com/gorriecoe/silverstripe-link
Its extremely similar to linkable

**Comment by muskie9** [comment]
Hi @sanderha, thanks for submitting the ticket noting this. We're currently working roadmapping an update across our modules that will handle moving away from Shea's module. We're working on ensuring all options available through linkable are covered, such as embedded objects.

We'll provide an update as soon as possible.

**Comment by elliot-sawyer** [comment]
👍 for @gorriecoe's link and linkfield modules.  As a co-maintainer of both modules I am a bit biased, but if there's anything I can do to help with this please let me know!

**Comment by michalkleiner** [comment]
@elliot-sawyer is there a way how to remove the need of adding `$this` to every field creation call? If that was gone, I'd be happy to switch, but within the context of edit form, I don't want to be passing the exact same context yet again to the field.

**Comment by lars-lemon8** [comment]
Hi Guys,

Bumping into this issue during the upgrade to SS4.11.   Can I expect trouble if I switch to https://github.com/dynamic/silverstripe-elemental-baseobject/pull/16 ?

**Comment by lars-lemon8** [comment]
Update:  merged #16 in a fork ,  and it seems to run without a hitch so far.

**Comment by jsirish** [comment]
we're moving closer to merging #16 and creating a new major version of this module
