### ISSUE TITLE
Update to only have Title

### ISSUE THREAD

**Issue by korthjp17** [dynamic/silverstripe-elemental-baseobject#3]
Do we want to update this to only have a title field and a checkbox for show/hide like the blocks?

**Comment by muskie9** [comment]
I think ideally yes.

**Comment by korthjp17** [comment]
Agreed. However, I think we have validation on the name field, assuming we take all validation off?

**Comment by jsirish** [comment]
Yeah, we should match the Elemental UX as much as possible
